config/routes.rb
Rails.application.routes.draw do
  get 'users/create'
  get 'users/new'
  get 'sessions/create'
  get 'sessions/new'
  get 'sessions/destroy'
  get 'passwords/create'
  get 'passwords/new'
  resources :passwords, controller: 'passwords', only: [:create, :new]
  resource :session, controller: 'sessions', only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tokens, only: [:create]
  root to: 'chats#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :require_login
  
  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @messages = Message.new
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Clearance::PasswordsController
  def create
  end

  def new
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def create
  end

  def new
  end

  def destroy
  end
end

app/controllers/tokens_controller.rb
require 'twilio-ruby'
class TokensController < ApplicationController
  # Requires the user to be logged in before creating token
  before_action :require_login

  def create
    # Define User Identity
    identity = current_user.email

    # Create Grant for Access Token
    grant = Twilio::JWT::AccessToken::ChatGrant.new
    grant.service_sid = ENV['TWILIO_CHAT_SERVICE_SID']

    # Create an Access Token
    token = Twilio::JWT::AccessToken.new(
        ENV['TWILIO_ACCOUNT_SID'],
        ENV['TWILIO_API_KEY'],
        ENV['TWILIO_API_SECRET'],
        [grant],
        identity: identity
    )

    # Generate the token and send to client
    render json: { identity: identity, token: token.to_jwt }
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def create
  end

  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chats/show.html.erb
<h1>Chat</h1>
<div class="chat">
  <div class="messages">
    <div class="message">
      <span class="user">User:</span> Let's chat!
    </div>
  </div>
  <form>
    <label for="message">Message:</label>
    <input type="text" id="message" placeholder="Enter your message..." />
    <button type="submit">Send</button>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsTalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js' %>
    <%= javascript_include_tag 'https://media.twiliocdn.com/sdk/js/chat/v3.0/twilio-chat.min.js' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <% if signed_in? %>
          Signed in as: <%= current_user.email %>
          <%= link_to 'Sign out', sign_out_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign in', sign_in_path %>
        <% end %>

        <div id="flash">
          <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
        </div>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container center-text">
  <h1>Let's Talk</h1>

  <p>
    <strong>Name:</strong>
  </p>
  <p>Chat Log</p>

  <div class="container">
    <h3 class=" text-center">Let's Talk</h3>
    <div>
        <div style="margin:auto">
            <div style="background:whitesmoke !important">
                <input placeholder="Type a message"/>
            </div>
        </div>
    </div>
  </div>



  <%= form_with model: @message do |f| %>
    <%= label_tag(:body, "Message") %>
    <%= text_field_tag(:body) %>
    <%= submit_tag("Send") %>
  <% end %>
</div>